# Generated by Django 2.2 on 2020-07-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll_number', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('address', models.TextField(max_length=250)),
            ],
        ),
    ]
